### ISSUE TITLE
The func.predefined rule is not valid for names that are judged to be variables

### ISSUE THREAD

**Issue by steve02081504** [Tatakinov/yayalint#3]
I have appended some functions defined in the ayc file to `func.predefined`, but it seems that lint treats the use of these functions as variables, so this rule does not work.
I have tried to move these new rules to `func.used`, but it doesn't seem to work either.

(By the way: `TOAUTOEX` and `CVAUTOEX` are now system functions in the latest version of yaya (in the old version, `TOAUTOEX` was a function defined in the underlying dic file.)

**Comment by Tatakinov** [comment]
There is no feature in `func.predefined` to suppress the display of warnings for functions that are recognized as variables.
This is because if yayalint reads all the dictionaries, it will be suppressed without that feature.

Now that we have implemented the feature to read the ayc file, the problem should be solved.
